# Generated by Django 6.0.3 on 2026-03-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_remove_portfolio_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(related_name='portfolios', through='stocks.PortfolioItem', to='stocks.stock'),
        ),
    ]
