# Generated by Django 5.2.12 on 2026-03-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_portfolio_description_alter_collection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='portfolio_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
