# Generated by Django 6.0.3 on 2026-03-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_portfolioitem_alter_portfolio_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='stocks',
        ),
    ]
